name: ci
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install
      - run: npm run all
      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4
        with:
          commit_message: Build project
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ['v2', 'v3']
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: '.nvmrc'
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_dir: '__tests__/fixtures/${{ matrix.config }}'
